const calendarDB = [
  {
    name: "Jan-2021",
    daysNumber: 31,
    firstWeekdayOfMonth: 5,
    rows: 5,
  },
  {
    name: "Feb-2021",
    daysNumber: 28,
    firstWeekdayOfMonth: 1,
    rows: 4,
  },
  {
    name: "Mar-2021",
    daysNumber: 31,
    firstWeekdayOfMonth: 1,
    rows: 5,
  },
  {
    name: "Apr-2021",
    daysNumber: 30,
    firstWeekdayOfMonth: 4,
    rows: 5,
  },
  {
    name: "May-2021",
    daysNumber: 31,
    firstWeekdayOfMonth: 6,
    rows: 6,
  },
  {
    name: "Jun-2021",
    daysNumber: 30,
    firstWeekdayOfMonth: 2,
    rows: 5,
  },
  {
    name: "Jul-2021",
    daysNumber: 31,
    firstWeekdayOfMonth: 4,
    rows: 5,
  },
  {
    name: "Aug-2021",
    daysNumber: 31,
    firstWeekdayOfMonth: 7,
    rows: 6,
  },
  {
    name: "Sep-2021",
    daysNumber: 30,
    firstWeekdayOfMonth: 3,
    rows: 5,
  },
  {
    name: "Oct-2021",
    daysNumber: 31,
    firstWeekdayOfMonth: 5,
    rows: 5,
  },
  {
    name: "Nov-2021",
    daysNumber: 30,
    firstWeekdayOfMonth: 1,
    rows: 5,
  },
  {
    name: "Dec-2021",
    daysNumber: 31,
    firstWeekdayOfMonth: 3,
    rows: 5,
  },

  {
    name: "Jan-2022",
    daysNumber: 31,
    firstWeekdayOfMonth: 6,
    rows: 5,
  },
  {
    name: "Feb-2022",
    daysNumber: 28,
    firstWeekdayOfMonth: 2,
    rows: 4,
  },
  {
    name: "Mar-2022",
    daysNumber: 31,
    firstWeekdayOfMonth: 2,
    rows: 5,
  },
  {
    name: "Apr-2022",
    daysNumber: 30,
    firstWeekdayOfMonth: 5,
    rows: 5,
  },
  {
    name: "May-2022",
    daysNumber: 31,
    firstWeekdayOfMonth: 7,
    rows: 6,
  },
  {
    name: "Jun-2022",
    daysNumber: 30,
    firstWeekdayOfMonth: 3,
    rows: 5,
  },
  {
    name: "Jul-2022",
    daysNumber: 31,
    firstWeekdayOfMonth: 5,
    rows: 5,
  },
  {
    name: "Aug-2022",
    daysNumber: 31,
    firstWeekdayOfMonth: 1,
    rows: 5,
  },
  {
    name: "Sep-2022",
    daysNumber: 30,
    firstWeekdayOfMonth: 4,
    rows: 5,
  },
  {
    name: "Oct-2022",
    daysNumber: 31,
    firstWeekdayOfMonth: 6,
    rows: 6,
  },
  {
    name: "Nov-2022",
    daysNumber: 30,
    firstWeekdayOfMonth: 2,
    rows: 5,
  },
  {
    name: "Dec-2022",
    daysNumber: 31,
    firstWeekdayOfMonth: 4,
    rows: 5,
  },
  {
    name: "Jan-2023",
    daysNumber: 31,
    firstWeekdayOfMonth: 7,
    rows: 6,
  },
  {
    name: "Feb-2023",
    daysNumber: 28,
    firstWeekdayOfMonth: 3,
    rows: 4,
  },
  {
    name: "Mar-2023",
    daysNumber: 31,
    firstWeekdayOfMonth: 3,
    rows: 5,
  },
  {
    name: "Apr-2023",
    daysNumber: 30,
    firstWeekdayOfMonth: 6,
    rows: 5,
  },
  {
    name: "May-2023",
    daysNumber: 31,
    firstWeekdayOfMonth: 1,
    rows: 5,
  },
  {
    name: "Jun-2023",
    daysNumber: 30,
    firstWeekdayOfMonth: 4,
    rows: 5,
  },
  {
    name: "Jul-2023",
    daysNumber: 31,
    firstWeekdayOfMonth: 6,
    rows: 6,
  },
  {
    name: "Aug-2023",
    daysNumber: 31,
    firstWeekdayOfMonth: 2,
    rows: 5,
  },
  {
    name: "Sep-2023",
    daysNumber: 30,
    firstWeekdayOfMonth: 5,
    rows: 5,
  },
  {
    name: "Oct-2023",
    daysNumber: 31,
    firstWeekdayOfMonth: 7,
    rows: 6,
  },
  {
    name: "Nov-2023",
    daysNumber: 30,
    firstWeekdayOfMonth: 3,
    rows: 5,
  },
  {
    name: "Dec-2023",
    daysNumber: 31,
    firstWeekdayOfMonth: 5,
    rows: 5,
  },
  {
    name: "Jan-2024",
    daysNumber: 31,
    firstWeekdayOfMonth: 1,
    rows: 5,
  },
  {
    name: "Feb-2024",
    daysNumber: 29,
    firstWeekdayOfMonth: 4,
    rows: 5,
  },
  {
    name: "Mar-2024",
    daysNumber: 31,
    firstWeekdayOfMonth: 5,
    rows: 5,
  },
  {
    name: "Apr-2024",
    daysNumber: 30,
    firstWeekdayOfMonth: 1,
    rows: 5,
  },
  {
    name: "May-2024",
    daysNumber: 31,
    firstWeekdayOfMonth: 3,
    rows: 5,
  },
  {
    name: "Jun-2024",
    daysNumber: 30,
    firstWeekdayOfMonth: 6,
    rows: 5,
  },
  {
    name: "Jul-2024",
    daysNumber: 31,
    firstWeekdayOfMonth: 1,
    rows: 5,
  },
  {
    name: "Aug-2024",
    daysNumber: 31,
    firstWeekdayOfMonth: 4,
    rows: 5,
  },
  {
    name: "Sep-2024",
    daysNumber: 30,
    firstWeekdayOfMonth: 7,
    rows: 6,
  },
  {
    name: "Oct-2024",
    daysNumber: 31,
    firstWeekdayOfMonth: 2,
    rows: 5,
  },
  {
    name: "Nov-2024",
    daysNumber: 30,
    firstWeekdayOfMonth: 5,
    rows: 5,
  },
  {
    name: "Dec-2024",
    daysNumber: 31,
    firstWeekdayOfMonth: 7,
    rows: 6,
  },
];

export default calendarDB;
